### ISSUE TITLE
Error file 20230604

### ISSUE THREAD

**Issue by jgfillman** [nickheyer/DiscoFlix#11]
[ERR_general_11d57a01-4fa5-4229-8da1-19104b186919.log](https://github.com/nickheyer/DiscoFlix/files/11644787/ERR_general_11d57a01-4fa5-4229-8da1-19104b186919.log)

**Comment by nickheyer** [comment]
> [ERR_general_11d57a01-4fa5-4229-8da1-19104b186919.log](https://github.com/nickheyer/DiscoFlix/files/11644787/ERR_general_11d57a01-4fa5-4229-8da1-19104b186919.log)
> 
> 
> 
> 

That's an interesting error. It implies that the request was never received by radarr/sonarr.

I will look more into this. Thanks.
